services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    image: splitty-web
    volumes:
      - static_volume:/home/appuser/static
      - media_volume:/home/appuser/media
      - ./docker/django/env.yaml:/home/appuser/env.yaml
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - pgsql
      - migration

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - static_volume:/home/appuser/static
      - media_volume:/home/appuser/media
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web

  redis:
    image: redis:7.2

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis

  pgsql:
    image: postgres:14.12
    volumes:
      - ./docker/postgres/data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_pass
      - POSTGRES_DB=django

  migration:
    image: splitty-web
    command: python manage.py migrate --noinput
    depends_on:
      - pgsql

volumes:
  static_volume:
  media_volume:
